databases:
  - name: newdb
    plan: free
    databaseName: new
    user: new

services:
  - type: web
    plan: free
    name: Personal-website
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: " gunicorn wsgi:application --bind 0.0.0.0:8000 "
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
